image:
  repository: friendly-app
  tag: 1.0.0
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 80
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: friendly-app.domain.com
      paths:
        - path: /
          backend:
            serviceName: friendly-app
            servicePort: 80
resources: {}
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
database:
  type: postgresql
  postgresql:
    host: postgres-host
    port: 5432
    username: user
    password: pass
    database: friendlyappdb
env:
  - name: DATABASE_URL
    value: "postgresql://user:pass@postgres-host:5432/friendlyappdb"

